### ISSUE TITLE
Missing swig

### ISSUE THREAD

**Issue by begreeen** [PW-Sat2/HAM-desktop-application#22]
```/home/pwsat2/main-without-exept/main/app/../grc_linux/grc_part -s "iq_file"
Traceback (most recent call last):
  File "grc_part.py", line 5, in <module>
  File "/tmp/pip-build-2Ia8pI/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "grc/source/file_source/iq_file_main.py", line 12, in <module>
  File "/tmp/pip-build-2Ia8pI/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "grc/source/file_source/file_source.py", line 13, in <module>
  File "/tmp/pip-build-2Ia8pI/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "gnuradio/blocks/__init__.py", line 32, in <module>
  File "/tmp/pip-build-2Ia8pI/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "gnuradio/blocks/blocks_swig.py", line 22, in <module>
  File "/tmp/pip-build-2Ia8pI/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "gnuradio/blocks/blocks_swig0.py", line 17, in <module>
  File "gnuradio/blocks/blocks_swig0.py", line 16, in swig_import_helper
  File "importlib/__init__.py", line 37, in import_module
ImportError: No module named _blocks_swig0
[2229] Failed to execute script grc_part```

**Comment by begreeen** [comment]
app should not be run from lower version of ubuntu (here freeze from 18.04 run on 17.10).
